### Get all profiles
GET http://localhost:3000/profiles

### Add a profile to the database 
POST http://localhost:3000/profiles
Content-Type: application/json

{
  "nickname": "XxDarkSasukexX",
  "firstname": "Killian",
  "lastname": "Lelouch"
}

### Get a profile of a given id
GET http://localhost:3000/profiles/1

### Edit a profile at the given id in the database
PUT http://localhost:3000/profiles/1
Content-Type: application/json

{
  "nickname": "Brolyus",
  "firstname": "Anthony",
  "lastname": "De Sousa"
}

### Delete a profile at the given id
DELETE http://localhost:3000/profiles/1
