### Get all the tags
GET http://localhost:3000/tags

### Add tags to the database
POST http://localhost:3000/tags
Content-Type: application/json

{
  "instrument": "flute de Pan",
  "status": "Amateur",
  "style": "Alternatif"
}

### Edit tags at the given id in the database
PUT http://localhost:3000/tags/1
Content-Type: application/json

{
  "instrument": "Guitare",
  "status": "Pro",
  "style": "Rock 60's"
}

### Delete tags at the given id in the database
DELETE http://localhost3000/tags/1