 
### Test the connection to the home page
GET http://localhost:3000/

### Get all profiles
GET http://localhost:3000/profiles

### Add a profile to the database 
POST http://localhost:3000/profiles
Content-Type: application/json

{
  "nickname": "XxDarkSasukexX",
  "firstname": "Killian",
  "lastname": "Lelouch"
}

### Edit a profile at the given id in the database
PUT http://localhost:3000/profiles/1

Content-Type: application/json
{
  "nickname": "Asomar",
  "firstname": "Pierre-Alban",
  "lastname": "Demars"
}

### Delete a profile at the given id
DELETE http://localhost:3000/profiles/1

### Get all the tags
GET http://localhost:3000/tags

### Add tags to the database
POST http://localhost:3000/tags
Content-Type: application/json

{
  "instrument": "flute de Pan",
  "status": "Amateur",
  "style": "Alternatif"
}

### Edit tags at the given id in the database
PUT http://localhost:3000/tags/1
Content-Type: application/json

{
  "instrument": "Guitare",
  "status": "Pro",
  "style": "Rock 60's"
}

### Delete tags at the given id in the database
DELETE http://localhost:3000/tags/1